import { join } from "node:path";
const { default: packageJson } = await import("../package.json", { with: { type: "json" } });

const { env } = process;
const SERVER_STARTUP = new Date();

const version = semverFromPackage();

const config = {
  version,
  startupTime: SERVER_STARTUP.toISOString(),
  httpPort: env.PORT ?? "9999",
  basePath: join(env.BASE_PATH ?? "", "/"),
  content: {
    appName: "hello-world-web",
    appVersion: env.APP_VERSION ?? version,
    appUrl: env.APP_URL ?? "https://github.com/eins78/hello-world-web",
    appTitle: env.APP_TITLE ?? `Hello World!`,
    appDescription: env.APP_DESCRIPTION ?? "A simple web server for testing and debugging web infrastructure.", // WARNING: Accepts HTML - only use trusted content to avoid XSS
    ciRunUrl: env.CI_RUN_URL, // Optional: link to CI run that deployed this version
    ciRunNumber: env.CI_RUN_NUMBER, // Optional: CI run number for display (e.g., "123")
    ciCommitSha: env.CI_COMMIT_SHA, // Optional: full commit SHA that was deployed
    ciCommitShortSha: env.CI_COMMIT_SHORT_SHA, // Optional: short commit SHA for display (generated by git)
    ciDockerImage: env.CI_DOCKER_IMAGE, // Optional: Docker image tag used for deployment (e.g., "sha-abc123...")
    garProjectId: env.GAR_PROJECT_ID, // Optional: Google Artifact Registry project ID
    garLocation: env.GAR_LOCATION, // Optional: Google Artifact Registry location (e.g., "europe-west6")
    garRepository: env.GAR_REPOSITORY, // Optional: Google Artifact Registry repository name
    garImageName: env.GAR_IMAGE_NAME ?? "hello-world-web", // Optional: GAR image name (defaults to appName)
  },
} as const;

export type Config = typeof config;
export default config;

// helper
function semverFromPackage() {
  return String(packageJson.version || "0.0.0-no.version.found");
}
