services:
  webserver:
    # use 'image' tag if it exists, or 'build' with this config and tag as such
    image: hello-world-web:latest
    build:
      context: .
    environment:
      - "PORT=${PORT?configure the http port!}"
      - "APP_TITLE=Hello docker-compose!"
      - 'APP_DESCRIPTION=This is an <a target="_blank" href="https://github.com/eins78/hello-world-web">open source</a> demo web server for testing and debugging web infrastructure.'
      - "BASE_PATH"
    ports:
      # format "host:container", container must match with environment.PORT
      - ${PORT}:${PORT}
    healthcheck:
      # see Dockerfile for command, or overwrite here with `test:`
      start_period: 1s
      timeout: 3s
      interval: 10s
      retries: 3
    env_file:
      - .env
