services:
  webserver:
    # use 'image' tag if it exists, or 'build' with this config and tag as such
    image: hello-world-web:latest
    build:
      context: .
    ports:
      # format "host:container", container must match with environment.PORT
      - ${PORT}:${PORT}
    healthcheck:
      # see Dockerfile for command, or overwrite here with `test:`
      start_period: 1s
      timeout: 3s
      interval: 10s
      retries: 3
    environment:
      - "PORT=${PORT}"
      - "TITLE=Hello docker-compose!"
