apiVersion: v1
kind: Service
metadata:
  name: hello-world-web
spec:
  selector:
    app: hello-world-web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: 8080
            - name: APP_TITLE
              value: Hello Kubernetes!
          imagePullPolicy: Always
