name: Claude Renovate Review

# This workflow reviews Renovate PRs with dynamic CI waiting (Claude-managed).
# It follows RENOVATE_PR_COMMENTS.md guidelines (≤3 lines, ≤200 chars).
# Security: Read-only, concise output enforced.

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  renovate-review:
    # Only run on Renovate PRs
    if: |
      github.event.pull_request.user.login == 'app/renovate' ||
      github.event.pull_request.user.login == 'renovate[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Review (Renovate Mode)
        id: claude-review
        uses: anthropics/claude-code-action@7b914ae5c08260c1ec0aecfbf27b76d71578102c
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            AUTHOR: ${{ github.event.pull_request.user.login }}

            This is a Renovate automated dependency update PR.

            **CRITICAL: You MUST follow docs/RENOVATE_PR_COMMENTS.md guidelines:**
            - Read docs/RENOVATE_PR_COMMENTS.md IMMEDIATELY
            - For CI GREEN: Maximum 3 lines, 200 characters
            - For CI FAILED: Use expanded diagnostic format with error logs and fix guidance
            - Default response when green: "✅ CI green." (if no issues)
            - Use format: [emoji] [one-line summary]

            **STEP 1: Wait for CI checks to complete (max 30 minutes)**

            Implement this wait loop:
            1. Run: `gh pr view ${{ github.event.pull_request.number }} --json statusCheckRollup`
            2. Parse the JSON output
            3. Count checks by status: COMPLETED, IN_PROGRESS, PENDING
            4. Exclude this workflow (renovate-review) and claude-review from wait checks
            5. If ALL other checks are COMPLETED → proceed to STEP 1.5
            6. If not complete:
               - Run: `sleep 30` (wait 30 seconds)
               - Increment counter
               - Repeat from step 1
            7. Maximum: 60 iterations (30 minutes total)
            8. After 30 min OR when complete → proceed to STEP 1.5

            **STEP 1.5: Check if PR is still open**

            After CI completes, check PR state before reviewing:
            1. Run: `gh pr view ${{ github.event.pull_request.number }} --json state,merged`
            2. Parse the output to get state and merged fields
            3. If state is "MERGED" or "CLOSED":
               - Output message: "PR already merged/closed, no review needed"
               - Exit gracefully (this is normal behavior, not an error)
               - DO NOT post any comment
            4. If state is "OPEN":
               - Continue to STEP 2 (review)

            **Important:** This check prevents posting comments on automerged PRs.
            Renovate automerges minor/patch updates when CI passes (see .renovaterc).
            This is expected behavior - automerge means the update was safe.

            **STEP 1.6: Collapse previous Claude comments**

            Before posting a new review, collapse any existing comments from previous runs:

            1. Get existing Claude comments:
               ```bash
               gh pr view ${{ github.event.pull_request.number }} --json comments \
                 --jq '.comments[] | select(.author.login == "claude") | {id: .id, body: .body, createdAt: .createdAt}'
               ```

            2. If comments exist:
               a. Get the MOST RECENT comment (last in the list)
               b. Check if it's already wrapped in <details> (grep for "<details>")
               c. If NOT already wrapped:
                  - Wrap the body in:
                    ```
                    <details>
                    <summary>⏳ Outdated review (superseded by new push)</summary>

                    [original body]

                    _Review from [createdAt]_
                    </details>
                    ```
                  - Extract comment ID from the node ID format (IC_...)
                  - Update via: gh api -X PATCH /repos/${{ github.repository }}/issues/comments/{comment_id} -f body="[wrapped]"

            3. Continue to STEP 2 (post new comment)

            **Benefits:**
            - Keeps thread clean (only latest expanded)
            - Preserves history (collapsed comments still accessible)
            - Shows timestamp on collapsed reviews

            **STEP 2: Review with CI results (only if PR still open)**

            Check CI results:
            - If all passed: "✅ CI green." (1 line)
            - If timeout: "⏳ CI incomplete after 30 min"
            - If ANY check failed: Follow CI failure diagnostic process below

            **STEP 3: If CI failed, provide diagnostics**

            When CI fails, provide expanded diagnostic information:
            1. Get failed run ID: `gh run list --branch {branch-name} --limit 5`
            2. Check logs: `gh run view {run-id} --log-failed`
            3. Review diff: `gh pr diff ${{ github.event.pull_request.number }}`
            4. Post diagnostic comment with:
               - Which check failed
               - 5-10 lines of relevant error output
               - Analysis of likely cause
               - Suggested fix steps

            See docs/RENOVATE_PR_COMMENTS.md ci_failure_handling section for format.

            Then comment using `gh pr comment`.
            Remember: CI failure comments are NOT subject to 3-line/200-char limits.

          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(gh run view:*),Bash(gh run list:*),Bash(gh api:*),Bash(sleep *)"'