name: Claude Renovate PR Handler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  handle-renovate-pr:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Auto-comment with Claude mention
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body || '';
            
            // Parse version table from PR description
            // Example: | package | `1.2.3` -> `2.0.0` | age | confidence |
            const versionMatch = prBody.match(/\|\s*`(\d+)\.(\d+)\.(\d+)`\s*->\s*`(\d+)\.(\d+)\.(\d+)`\s*\|/);
            let updateType = 'UNKNOWN';
            let oldVersion = '';
            let newVersion = '';
            
            if (versionMatch) {
              const [, oldMajor, oldMinor, oldPatch, newMajor, newMinor, newPatch] = versionMatch;
              oldVersion = `${oldMajor}.${oldMinor}.${oldPatch}`;
              newVersion = `${newMajor}.${newMinor}.${newPatch}`;
              
              if (newMajor > oldMajor) {
                updateType = 'MAJOR';
              } else if (newMinor > oldMinor) {
                updateType = 'MINOR';
              } else if (newPatch > oldPatch) {
                updateType = 'PATCH';
              }
            }
            
            // Extract merge confidence level from badges
            const confidenceMatch = prBody.match(/confidence\/npm\/[^/]+\/[^/]+\/[^?]+/);
            const hasHighConfidence = prBody.includes('confidence') && 
                                    (prBody.includes('high') || prBody.includes('very-high'));
            const hasLowConfidence = prBody.includes('confidence') && 
                                   (prBody.includes('low') || prBody.includes('very-low'));
            
            let comment = `@claude This is an automated Renovate dependency update PR.
            
            **IMPORTANT**: Read RENOVATE.md for complete instructions on handling dependency updates.
            
            **PR Details:**
            - Update Type: **${updateType}**${oldVersion && newVersion ? ` (${oldVersion} → ${newVersion})` : ''}
            - PR Title: ${pr.title}
            - Merge Confidence: ${hasHighConfidence ? '✅ HIGH' : hasLowConfidence ? '⚠️ LOW' : '➖ NEUTRAL/UNKNOWN'}
            
            **Quick Summary:**
            1. Read RENOVATE.md for the complete workflow
            2. Work on this ONE PR only (don't touch other Renovate PRs)
            3. Either fix and merge OR skip with @eins78 mention
            4. Use Dependency Dashboard to request next PR
            5. Continue until ALL updates are handled
            
            **Decision Hints:**
            ${updateType === 'PATCH' ? '- PATCH update: Usually safe, fix CI and merge' : ''}
            ${updateType === 'MINOR' ? '- MINOR update: Check for deprecations, usually safe' : ''}
            ${updateType === 'MAJOR' ? '- MAJOR update: Check changelog for breaking changes!' : ''}
            ${hasHighConfidence ? '- High merge confidence: Lower risk of issues' : ''}
            ${hasLowConfidence ? '- Low merge confidence: Extra caution needed, review carefully' : ''}
            
            **Key Rules:**
            - Never work on multiple PRs (pnpm lockfile conflicts)
            - Process every update until Dashboard is clear
            - Follow the skip criteria in RENOVATE.md section 4`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: comment
            });
            
      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: "60"