name: Claude Renovate PR Handler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  handle-renovate-pr:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Auto-comment with Claude mention
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body || '';
            
            // Extract update type and package info from PR title/body
            const isMinorPatch = prBody.includes('minor') || prBody.includes('patch');
            const isMajor = prBody.includes('major');
            
            let comment = `@claude This is an automated Renovate dependency update PR.
            
            **IMPORTANT**: Read RENOVATE.md for complete instructions on handling dependency updates.
            
            **PR Details:**
            - Update Type: ${isMajor ? 'MAJOR' : isMinorPatch ? 'MINOR/PATCH' : 'UNKNOWN'}
            - PR Title: ${pr.title}
            
            **Quick Summary:**
            1. Read RENOVATE.md for the complete workflow
            2. Work on this ONE PR only (don't touch other Renovate PRs)
            3. Either fix and merge OR skip with @eins78 mention
            4. Use Dependency Dashboard to request next PR
            5. Continue until ALL updates are handled
            
            **Key Rules:**
            - Never work on multiple PRs (pnpm lockfile conflicts)
            - Process every update until Dashboard is clear
            - Follow the skip criteria in RENOVATE.md section 4`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: comment
            });
            
      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: "60"