name: End-to-End Tests

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install pnpm with corepack
        run: corepack enable && npm i -g corepack && pnpm -v

      - name: Install and Build with cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: .
          install: pnpm --recursive install --frozen-lockfile --ignore-scripts
          build: pnpm run build
          runTests: false

      - name: Run tests with cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./packages/e2e-tests
          install: false
          start: pnpm --dir ../.. run start
          browser: chrome
          wait-on: http://localhost:11111
          wait-on-timeout: 60
          config: |
            {
              "video": true,
              "screenshotsFolder": "cypress/screenshots",
              "videosFolder": "cypress/videos"
            }
        env:
          CYPRESS_port: 3333
          PORT: 11111

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            packages/e2e-tests/cypress/screenshots
            packages/e2e-tests/cypress/videos
